map_merge:
  ros__parameters:
    number_of_robots: 4
    merging_rate: 4.0
    discovery_rate: 0.05
    estimation_rate: 0.5
    estimation_confidence: 0.6
    robot_map_topic: map
    robot_map_updates_topic: map_updates
    robot_namespace: ""
    merged_map_topic: map
    world_frame: world
    known_init_poses: true

    # Define here robots' positions in the map if known_init_poses is true
    /robot1/map_merge/init_pose_x: -3.0
    /robot1/map_merge/init_pose_y: 3.0
    /robot1/map_merge/init_pose_z: 0.0
    /robot1/map_merge/init_pose_yaw: 0.0

    /robot2/map_merge/init_pose_x: 0.5
    /robot2/map_merge/init_pose_y: 0.0
    /robot2/map_merge/init_pose_z: 0.0
    /robot2/map_merge/init_pose_yaw: 0.0
    
    /robot3/map_merge/init_pose_x: 2.0
    /robot3/map_merge/init_pose_y: 1.0
    /robot3/map_merge/init_pose_z: 0.0
    /robot3/map_merge/init_pose_yaw: 0.0

    /robot4/map_merge/init_pose_x: 2.0
    /robot4/map_merge/init_pose_y: -1.5
    /robot4/map_merge/init_pose_z: 0.0
    /robot4/map_merge/init_pose_yaw: 0.0

    /robot5/map_merge/init_pose_x: 10.0
    /robot5/map_merge/init_pose_y: 0.0
    /robot5/map_merge/init_pose_z: 0.0
    /robot5/map_merge/init_pose_yaw: 0.0

    /robot6/map_merge/init_pose_x: -10.0
    /robot6/map_merge/init_pose_y: 0.0
    /robot6/map_merge/init_pose_z: 0.0
    /robot6/map_merge/init_pose_yaw: 0.0

    /robot7/map_merge/init_pose_x: 10.0
    /robot7/map_merge/init_pose_y: 0.0
    /robot7/map_merge/init_pose_z: 0.0
    /robot7/map_merge/init_pose_yaw: 0.0

    /robot8/map_merge/init_pose_x: -1.0
    /robot8/map_merge/init_pose_y: 1.0
    /robot8/map_merge/init_pose_z: 0.0
    /robot8/map_merge/init_pose_yaw: 0.0
